/**
 * Per-endpoint response-body contracts for validate-response-bodies.js.
 *
 * Each entry:
 *   name        display name (matches the .upptimerc.yml site name)
 *   keyEnv      which API-key secret to send (free vs Pro+ tier)
 *   method      GET | POST
 *   url         full request URL (query string included for GET)
 *   body        request body object (POST only)
 *   expectStatus    expected HTTP status (default 200)
 *   requireStrictJson  if false, a NaN/Infinity token is a warning not a failure
 *   checks      array of assertions on the parsed body
 *
 * Check fields: path (required); optional type ('string'|'number'|'integer'|
 *   'boolean'|'array'|'object'), equals, nonEmpty, minLength, minKeys, gt, min,
 *   match (regex source); severity 'hard' (default) | 'soft'.
 *   Path syntax: dot keys, [index], and `*` = first entry of an object map/array.
 *
 * Design: HARD checks assert the structural contract + identity + stable
 * datasets. SOFT checks cover values that can legitimately vary off-hours
 * (sparse realtime quote/trade/tick arrays) or known upstream quirks.
 *
 * This file is NOT regenerated by Upptime's update-template workflow.
 */

const PROPLUS = 'PRIXE_PRO_PLUS_API_KEY';
const FREE = 'PRIXE_API_KEY';

module.exports = [
  // ---- Core (free tier) ----------------------------------------------------
  {
    name: 'Search API',
    keyEnv: FREE,
    method: 'POST',
    url: 'https://api.prixe.io/api/search',
    body: { query: 'Apple' }, // name-substring search; "AAPL" returns 0 (no name contains it)
    requireStrictJson: false, // upstream returns cik as NaN for some rows (reported as a warning)
    checks: [
      { path: 'success', equals: true },
      { path: 'data', type: 'array', minLength: 1 },
      { path: 'data[0].stockName', type: 'string', nonEmpty: true },
      { path: 'data[0].ticker', type: 'string', nonEmpty: true },
      { path: 'data[0].cusip', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'Last Sold Price API',
    keyEnv: FREE,
    method: 'POST',
    url: 'https://api.prixe.io/api/last_sold',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'ticker', equals: 'AAPL' },
      { path: 'lastSalePrice', type: 'string', match: '\\d' },
      { path: 'lastTradeTimestamp', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'Historical Price API',
    keyEnv: FREE,
    method: 'POST',
    url: 'https://api.prixe.io/api/price',
    body: { ticker: 'AAPL', start_date: '2025-01-01', end_date: '2025-01-15', interval: '1d' },
    checks: [
      { path: 'success', equals: true },
      { path: 'data.ticker', equals: 'AAPL' },
      { path: 'data.close', type: 'array', minLength: 1 },
      { path: 'data.timestamp', type: 'array', minLength: 1 },
      { path: 'data.volume', type: 'array', minLength: 1 },
    ],
  },
  {
    name: 'Market Stats API',
    keyEnv: FREE,
    method: 'POST',
    url: 'https://api.prixe.io/api/stats',
    body: { data_type: 'gainers' },
    checks: [
      { path: 'success', equals: true },
      { path: 'data_type', equals: 'gainers' },
      { path: 'data', type: 'array', minLength: 1 },
      { path: 'data[0].ticker', type: 'string', nonEmpty: true },
      { path: 'data[0].regularMarketPrice', type: 'number' },
    ],
  },
  {
    name: 'News API',
    keyEnv: FREE,
    method: 'POST',
    url: 'https://api.prixe.io/api/news',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'success', equals: true },
      { path: 'news_data.data', type: 'array', minLength: 1 },
      { path: 'news_data.data[0].title', type: 'string', nonEmpty: true },
      { path: 'news_data.data[0].url', type: 'string', nonEmpty: true },
    ],
  },

  // ---- SEC / fundamentals (Pro+) ------------------------------------------
  {
    name: 'Stock Splits API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/splits',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'ticker', equals: 'AAPL' },
      { path: 'splits', type: 'array', minLength: 1 },
      { path: 'splits[0].date', type: 'string', nonEmpty: true },
      { path: 'splits[0].ratio', type: 'number' },
    ],
  },
  {
    name: 'SEC Forms List API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/forms?ticker=AAPL',
    checks: [
      { path: 'success', equals: true },
      { path: 'ticker', equals: 'AAPL' },
      { path: 'forms', type: 'array', minLength: 1 },
      { path: 'forms[0].form', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'SEC Forms Data API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/forms',
    body: { ticker: 'AAPL', form: '10-K', year: 2024 },
    checks: [
      { path: 'success', equals: true },
      { path: 'ticker', equals: 'AAPL' },
      { path: 'filings.data', type: 'array', minLength: 1 },
      { path: 'filings.data[0].form', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'SEC Financials API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/forms/financials',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'success', equals: true },
      { path: 'ticker', equals: 'AAPL' },
      { path: 'annual.data', type: 'array', minLength: 1 },
      { path: 'annual.data[0].metrics', type: 'object', minKeys: 1 },
      { path: 'quarterly.data', type: 'array', minLength: 1 },
    ],
  },
  {
    name: 'Board Members API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/board_members',
    body: { ticker: 'AAPL', articles: false },
    checks: [
      { path: 'success', equals: true },
      { path: 'ticker', equals: 'AAPL' },
      { path: 'board_members.data', type: 'array', minLength: 1 },
      { path: 'board_members.data[0].name', type: 'string', nonEmpty: true },
    ],
  },

  // ---- Politicians (Pro+) --------------------------------------------------
  {
    name: 'Politicians API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/politicians',
    body: { year: 2024, ticker: 'AAPL', limit: 50, offset: 0 },
    checks: [
      { path: 'success', equals: true },
      { path: 'total', type: 'integer' },
      { path: 'transactions', type: 'array', minLength: 1 },
      { path: 'transactions[0]', type: 'object', minKeys: 1 },
    ],
  },
  {
    name: 'Politicians List API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/politicians/list',
    body: { year: 2024, chamber: 'senate', limit: 50, offset: 0 },
    checks: [
      { path: 'success', equals: true },
      { path: 'politicians', type: 'array', minLength: 1 },
      { path: 'politicians[0].politician', type: 'string', nonEmpty: true },
      { path: 'politicians[0].chamber', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'Politicians Holdings API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/politicians/holdings',
    body: { politician: 'pelosi', year: 2024, limit: 50, offset: 0 },
    checks: [
      { path: 'success', equals: true },
      { path: 'activity', type: 'array', minLength: 1 },
      { path: 'activity[0].asset_name', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'Politicians Executive Disclosures API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/politicians/executive_disclosures',
    body: { limit: 50, offset: 0 },
    checks: [
      { path: 'success', equals: true },
      { path: 'total', type: 'integer' },
      { path: 'filings', type: 'array', minLength: 1 },
      { path: 'filings[0].filer_name', type: 'string', nonEmpty: true },
    ],
  },

  // ---- Calendars (Pro+) — array may legitimately be empty on quiet days ----
  {
    name: 'IPO Calendar API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/ipo_calendar',
    body: { month: '2025-05' }, // fixed past month -> stable, non-empty
    checks: [
      { path: 'success', equals: true },
      { path: 'month', equals: '2025-05' },
      { path: 'counts.priced', type: 'integer' },
      { path: 'priced', type: 'array', minLength: 1 },
    ],
  },
  {
    name: 'Dividends Calendar API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/dividends_calendar',
    body: {},
    checks: [
      { path: 'success', equals: true },
      { path: 'date', type: 'string', nonEmpty: true },
      { path: 'count', type: 'integer' },
      { path: 'dividends', type: 'array' },
      { path: 'dividends', type: 'array', minLength: 1, severity: 'soft' },
    ],
  },
  {
    name: 'Earnings Calendar API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/earnings_calendar',
    body: {},
    checks: [
      { path: 'success', equals: true },
      { path: 'date', type: 'string', nonEmpty: true },
      { path: 'count', type: 'integer' },
      { path: 'earnings', type: 'array' },
      { path: 'earnings', type: 'array', minLength: 1, severity: 'soft' },
    ],
  },
  {
    name: 'Economic Calendar API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/economic_calendar',
    body: {},
    checks: [
      { path: 'success', equals: true },
      { path: 'date', type: 'string', nonEmpty: true },
      { path: 'count', type: 'integer' },
      { path: 'events', type: 'array' },
      { path: 'events', type: 'array', minLength: 1, severity: 'soft' },
    ],
  },

  // ---- Nasdaq feed (Pro+) --------------------------------------------------
  {
    name: 'Nasdaq Snapshot API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/nasdaq/snapshot?tickers=AAPL,MSFT&category=US_STOCK',
    checks: [
      { path: '', type: 'array', minLength: 1 },
      { path: '[0].ticker', type: 'string', nonEmpty: true },
      { path: '[0].price', type: 'string', match: '\\d' },
    ],
  },
  {
    name: 'Nasdaq Quotes API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/nasdaq/quotes?ticker=AAPL&category=US_STOCK',
    checks: [
      { path: 'ticker', equals: 'AAPL' },
      { path: 'quote_time', type: 'number' },
      { path: 'bids', type: 'array' },
      { path: 'asks', type: 'array' },
      { path: 'bids', type: 'array', minLength: 1, severity: 'soft' }, // empty off-hours
    ],
  },
  {
    name: 'Nasdaq Tick API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/nasdaq/tick?ticker=AAPL&category=US_STOCK&count=10',
    checks: [
      { path: 'ticker', equals: 'AAPL' },
      { path: 'result', type: 'array' },
      { path: 'result', type: 'array', minLength: 1, severity: 'soft' },
      { path: 'result[0].price', type: 'string', match: '\\d', severity: 'soft' },
    ],
  },
  {
    name: 'Nasdaq Bars API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/nasdaq/bars?ticker=AAPL&category=US_STOCK&timespan=D&count=10',
    checks: [
      { path: '', type: 'array', minLength: 1 },
      { path: '[0].ticker', type: 'string', nonEmpty: true },
      { path: '[0].close', type: 'string', match: '\\d' },
      { path: '[0].time', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'Nasdaq Batch Bars API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/nasdaq/batch_bars',
    body: { tickers: ['AAPL', 'MSFT', 'NVDA'], category: 'US_STOCK', timespan: 'D', count: 3 },
    checks: [
      { path: 'result', type: 'array', minLength: 1 },
      { path: 'result[0].ticker', type: 'string', nonEmpty: true },
      { path: 'result[0].result', type: 'array', minLength: 1 },
    ],
  },

  // ---- Crypto (Pro+) — 24/7 markets ---------------------------------------
  {
    name: 'Crypto Market Data API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/crypto',
    body: { type: 'snapshot', tickers: ['BTC', 'ETH'] },
    checks: [
      { path: '', type: 'array', minLength: 1 },
      { path: '[0].ticker', type: 'string', nonEmpty: true },
      { path: '[0].price', type: 'string', match: '\\d' },
    ],
  },
  {
    name: 'Crypto Pairs List API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/crypto/list',
    checks: [
      { path: '', type: 'array', minLength: 1 },
      { path: '[0].ticker', type: 'string', nonEmpty: true },
      { path: '[0].currency', type: 'string', nonEmpty: true },
    ],
  },

  // ---- Alpaca IEX feed (Pro+) ---------------------------------------------
  {
    name: 'IEX Bars API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/iex/bars',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'bars', type: 'object', minKeys: 1 },
      { path: 'bars.AAPL', type: 'array', minLength: 1 },
      { path: 'bars.AAPL[0].close', type: 'number' },
      { path: 'bars.AAPL[0].timestamp', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'IEX Quotes API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/iex/quotes',
    body: { ticker: 'AAPL', latest: true },
    checks: [
      { path: 'quotes.AAPL', type: 'object', minKeys: 1 },
      { path: 'quotes.AAPL.timestamp', type: 'string', nonEmpty: true },
      { path: 'quotes.AAPL.bid_price', type: 'number' },
      { path: 'quotes.AAPL.tape', type: 'string', nonEmpty: true },
      { path: 'quotes.AAPL.bid_price', gt: 0, severity: 'soft' },
    ],
  },
  {
    name: 'IEX Trades API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/iex/trades',
    body: { ticker: 'AAPL', latest: true },
    checks: [
      { path: 'trades.AAPL', type: 'object', minKeys: 1 },
      { path: 'trades.AAPL.price', type: 'number' },
      { path: 'trades.AAPL.timestamp', type: 'string', nonEmpty: true },
      { path: 'trades.AAPL.size', type: 'number' },
      { path: 'trades.AAPL.price', gt: 0, severity: 'soft' },
    ],
  },
  {
    name: 'IEX Snapshot API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/iex/snapshot',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'snapshots.AAPL', type: 'object', minKeys: 1 },
      { path: 'snapshots.AAPL.daily_bar.close', type: 'number' },
      { path: 'snapshots.AAPL.latest_quote', type: 'object', minKeys: 1 },
    ],
  },

  // ---- Alpaca SIP feed (Pro+) ---------------------------------------------
  {
    name: 'SIP Bars API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/sip/bars',
    body: { ticker: 'AAPL', timeframe: '1Day', limit: 5 },
    checks: [
      { path: 'bars.AAPL', type: 'array', minLength: 1 },
      { path: 'bars.AAPL[0].close', type: 'number' },
      { path: 'bars.AAPL[0].timestamp', type: 'string', nonEmpty: true },
    ],
  },
  {
    name: 'SIP Quotes API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/sip/quotes',
    body: { ticker: 'AAPL', latest: true },
    checks: [
      { path: 'quotes.AAPL', type: 'object', minKeys: 1 },
      { path: 'quotes.AAPL.timestamp', type: 'string', nonEmpty: true },
      { path: 'quotes.AAPL.bid_price', type: 'number' },
      { path: 'quotes.AAPL.ask_price', type: 'number' },
      { path: 'quotes.AAPL.bid_price', gt: 0, severity: 'soft' },
    ],
  },
  {
    name: 'SIP Trades API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/sip/trades',
    body: { ticker: 'AAPL', latest: true },
    checks: [
      { path: 'trades.AAPL', type: 'object', minKeys: 1 },
      { path: 'trades.AAPL.price', type: 'number' },
      { path: 'trades.AAPL.timestamp', type: 'string', nonEmpty: true },
      { path: 'trades.AAPL.size', type: 'number' },
      { path: 'trades.AAPL.price', gt: 0, severity: 'soft' },
    ],
  },
  {
    name: 'SIP Snapshot API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/sip/snapshot',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'snapshots.AAPL', type: 'object', minKeys: 1 },
      { path: 'snapshots.AAPL.daily_bar.close', type: 'number' },
      { path: 'snapshots.AAPL.latest_quote', type: 'object', minKeys: 1 },
    ],
  },
  {
    name: 'SIP Movers API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/sip/movers?top=10',
    checks: [
      { path: 'last_updated', type: 'string', nonEmpty: true },
      { path: 'gainers', type: 'array' },
      { path: 'losers', type: 'array' },
      { path: 'gainers', type: 'array', minLength: 1, severity: 'soft' },
      { path: 'gainers[0].ticker', type: 'string', nonEmpty: true, severity: 'soft' },
    ],
  },
  {
    name: 'SIP Most Actives API',
    keyEnv: PROPLUS,
    method: 'GET',
    url: 'https://api.prixe.io/api/sip/most_actives?by=volume&top=10',
    checks: [
      { path: 'last_updated', type: 'string', nonEmpty: true },
      { path: 'most_actives', type: 'array', minLength: 1 },
      { path: 'most_actives[0].ticker', type: 'string', nonEmpty: true },
      { path: 'most_actives[0].volume', type: 'number' },
    ],
  },

  // ---- Corporate actions & options (Pro+) ---------------------------------
  {
    name: 'Corporate Actions API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/corporate_actions',
    body: { ticker: 'AAPL' },
    checks: [
      { path: 'corporate_actions', type: 'object', minKeys: 1 },
      { path: 'corporate_actions.cash_dividends', type: 'array', minLength: 1, severity: 'soft' },
    ],
  },
  {
    name: 'Options API',
    keyEnv: PROPLUS,
    method: 'POST',
    url: 'https://api.prixe.io/api/options',
    body: { type: 'chain', ticker: 'AAPL' },
    checks: [
      { path: 'snapshots', type: 'object', minKeys: 1 },
      { path: 'snapshots.*.daily_bar', type: 'object', minKeys: 1, severity: 'soft' },
      { path: 'snapshots.*.latest_quote', type: 'object', minKeys: 1 },
    ],
  },
];
