# Upptime Configuration for Prixe Stock Data API
# Documentation: https://upptime.js.org/docs/configuration

# =============================================================================
# REPOSITORY SETTINGS
# =============================================================================
# IMPORTANT: Update these values with your GitHub username and repository name
owner: prixe-api
repo: prixe-status-page      # Replace with your repository name if different

user-agent: prixe-api-monitor

# =============================================================================
# MONITORED ENDPOINTS
# =============================================================================
# Your API key should be stored as a GitHub secret named PRIXE_API_KEY
# Go to: Repository Settings > Secrets and variables > Actions > New repository secret

sites:
  # WebSocket Server Health Check
  # Simple GET to verify the WebSocket server is responding
  # Without upgrade headers, server returns 426 (Upgrade Required) confirming it's alive
  - name: WebSocket Server
    url: https://ws.prixe.io/ws
    method: GET
    expectedStatusCodes:
      - 426  # Upgrade Required (server is alive, needs WebSocket upgrade)
      - 400  # Bad Request (server responding, missing upgrade headers)
      - 200  # OK (if server has a health endpoint)
    maxResponseTime: 10000
    icon: https://prixe.io/static/images/prixe.png

  # Search API Endpoint - Tests authenticated POST request
  - name: Search API
    url: https://api.prixe.io/api/search
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"query": "AAPL"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    icon: https://prixe.io/static/images/prixe.png

  # Last Sold Price API - Tests real-time price endpoint
  - name: Last Sold Price API
    url: https://api.prixe.io/api/last_sold
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"ticker": "AAPL"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 15000
    icon: https://prixe.io/static/images/prixe.png

  # Historical Price API - Tests historical data endpoint
  - name: Historical Price API
    url: https://api.prixe.io/api/price
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"ticker": "AAPL", "start_date": "2025-01-01", "end_date": "2025-01-15", "interval": "1d"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 20000
    icon: https://prixe.io/static/images/prixe.png

  # Market Statistics API - Tests market data endpoint
  - name: Market Stats API
    url: https://api.prixe.io/api/stats
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"data_type": "gainers"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 15000
    icon: https://prixe.io/static/images/prixe.png

  # News API - Tests news fetching endpoint
  - name: News API
    url: https://api.prixe.io/api/news
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"ticker": "AAPL"}'
    expectedStatusCodes:
      - 200
    # News API can take up to 10 seconds for non-cached responses
    maxResponseTime: 30000
    icon: https://prixe.io/static/images/prixe.png

  # SEC Forms API (GET) - Available SEC Forms (Pro+ Feature)
  - name: SEC Forms List API
    url: https://api.prixe.io/api/forms?ticker=AAPL
    method: GET
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
    expectedStatusCodes:
      - 200
      - 401  # May return 401 if not Pro+ subscription
    maxResponseTime: 15000
    icon: https://prixe.io/static/images/prixe.png

  # SEC Forms API (POST) - SEC Form Data (Pro+ Feature)
  - name: SEC Forms Data API
    url: https://api.prixe.io/api/forms
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"ticker": "AAPL", "form": "10-K", "year": 2024}'
    expectedStatusCodes:
      - 200
      - 401  # May return 401 if not Pro+ subscription
    maxResponseTime: 20000
    icon: https://prixe.io/static/images/prixe.png

  # Board Members API (Pro+ Feature)
  - name: Board Members API
    url: https://api.prixe.io/api/board_members
    method: POST
    headers:
      - "Authorization: Bearer $PRIXE_API_KEY"
      - "Content-Type: application/json"
    body: '{"ticker": "AAPL", "articles": false}'
    expectedStatusCodes:
      - 200
      - 401  # May return 401 if not Pro+ subscription
    maxResponseTime: 15000
    icon: https://prixe.io/static/images/prixe.png

# =============================================================================
# STATUS WEBSITE CONFIGURATION
# =============================================================================
status-website:
  # Site branding
  name: Prixe API Status
  logoUrl: https://prixe.io/static/images/prixe.png
  
  # Theme: light, dark, night, or ocean
  theme: light
  
  # Custom domain
  cname: status.prixe.io
  
  # Navigation bar links
  navbar:
    - title: Status
      href: /
    - title: API Documentation
      href: https://prixe.io/docs
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  # Introduction text on the status page
  introTitle: "**Prixe Stock Data API** Status"
  introMessage: |
    This page provides real-time status information for the Prixe Stock Data API.
    
    Our API provides real-time and historical stock market data with Bearer token authentication.
    
    **Base URL:** `https://api.prixe.io`
    
    **WebSocket:** `wss://ws.prixe.io/ws`

  # Favicon
  favicon: https://prixe.io/static/images/prixe.png

  # Custom CSS to match Prixe site styling
  css: |
    :root {
      --primary-color: #6366f1;
      --primary-hover: #4f46e5;
      --accent-color: #ec4899;
      --background-color: #ffffff;
      --secondary-background: #f9fafb;
      --text-color: #1e293b;
      --text-light: #64748b;
      --border-color: #e2e8f0;
    }
    
    * {
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      background-color: var(--background-color);
      color: var(--text-color);
    }
    
    /* Header/Navbar */
    nav, header, .navbar {
      background-color: var(--background-color) !important;
      box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
      border-bottom: 1px solid var(--border-color);
    }
    
    nav a, .navbar a {
      color: var(--text-color) !important;
      font-weight: 500;
      transition: color 0.3s ease;
    }
    
    nav a:hover, .navbar a:hover {
      color: var(--primary-color) !important;
    }
    
    /* Main content */
    main {
      background-color: var(--secondary-background);
    }
    
    /* Cards */
    .card, article, section {
      background-color: var(--background-color);
      border-radius: 0.75rem;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
      border: 1px solid var(--border-color);
    }
    
    /* Status indicators */
    .status-up, .up, [class*="up"] {
      color: #10b981 !important;
    }
    
    .status-down, .down, [class*="down"] {
      color: #ef4444 !important;
    }
    
    /* Links */
    a {
      color: var(--primary-color);
      transition: color 0.3s ease;
    }
    
    a:hover {
      color: var(--primary-hover);
    }
    
    /* Buttons */
    button, .btn {
      background-color: var(--primary-color);
      color: white;
      border-radius: 0.5rem;
      padding: 0.625rem 1.25rem;
      font-weight: 500;
      transition: all 0.3s ease;
      border: none;
    }
    
    button:hover, .btn:hover {
      background-color: var(--primary-hover);
    }
    
    /* Headings */
    h1, h2, h3, h4, h5, h6 {
      color: var(--text-color);
      font-weight: 700;
      line-height: 1.2;
    }
    
    h1 {
      font-size: 2.25rem;
      letter-spacing: -0.025em;
    }
    
    /* Footer */
    footer {
      background-color: var(--background-color);
      border-top: 1px solid var(--border-color);
      color: var(--text-light);
    }
    
    /* Progress bars / uptime bars */
    .progress, .bar {
      background-color: var(--secondary-background);
      border-radius: 0.5rem;
    }
    
    .progress-bar, .bar-fill {
      background-color: var(--primary-color);
      border-radius: 0.5rem;
    }
    
    /* Tables */
    table {
      border-collapse: collapse;
    }
    
    th, td {
      border-bottom: 1px solid var(--border-color);
      padding: 0.75rem 1rem;
    }
    
    th {
      color: var(--text-light);
      font-weight: 600;
      text-transform: uppercase;
      font-size: 0.75rem;
      letter-spacing: 0.05em;
    }
    
    /* Graphs */
    .chart-container {
      background-color: var(--background-color);
      border-radius: 0.75rem;
      padding: 1rem;
    }

# =============================================================================
# NOTIFICATION SETTINGS (Optional)
# =============================================================================
# Configure notifications in repository secrets. See: https://upptime.js.org/docs/notifications
# 
# Supported services:
# - Slack: NOTIFICATION_SLACK_WEBHOOK
# - Discord: NOTIFICATION_DISCORD_WEBHOOK  
# - Telegram: NOTIFICATION_TELEGRAM_BOT_KEY, NOTIFICATION_TELEGRAM_CHAT_ID
# - Email (via SMTP): NOTIFICATION_SMTP_HOST, NOTIFICATION_SMTP_PORT, etc.

# =============================================================================
# ISSUE ASSIGNEES (Optional)
# =============================================================================
# Users to assign when downtime issues are created
# assignees:
#   - YOUR_GITHUB_USERNAME

# =============================================================================
# WORKFLOW SCHEDULE
# =============================================================================
# Customize how often checks run (cron syntax)
workflowSchedule:
  uptime: "0 * * * *"          # Check uptime every hour
  responseTime: "0 * * * *"    # Record response time every hour
  graphs: "0 0 * * *"          # Update graphs daily at midnight
  staticSite: "0 1 * * *"      # Rebuild static site daily at 1 AM
  summary: "0 0 * * *"         # Update summary daily at midnight

# =============================================================================
# COMMIT SETTINGS
# =============================================================================
# Using Upptime defaults - custom messages can break emoji parsing for status detection

# =============================================================================
# ADDITIONAL SETTINGS
# =============================================================================
# Skip auto-deleting issues that are resolved within 15 minutes
skipDeleteIssues: false

# Skip repository metadata updates
# skipDescriptionUpdate: true
# skipTopicsUpdate: true
# skipHomepageUpdate: true
